import express from 'express';
import type { Request, Response } from 'express';
import http from 'http';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { GoogleGenAI, GenerateVideosOperation, Modality, LiveServerMessage } from '@google/genai';
import { WebSocketServer, WebSocket } from 'ws';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PORT = Number(process.env.PORT) || 3000;

// Initialize Google GenAI on the server
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

function formatGeminiError(err: any): { error: string; isBillingError: boolean; billingUrl?: string } {
  const errMsg = err?.message || (typeof err === 'string' ? err : JSON.stringify(err));
  const isBilling =
    errMsg.includes('402') ||
    errMsg.includes('prepayment credits') ||
    errMsg.includes('depleted') ||
    errMsg.includes('RESOURCE_EXHAUSTED') ||
    err?.status === 402 ||
    err?.code === 402;

  if (isBilling) {
    return {
      error:
        'Your AI Studio prepayment credits are depleted. Please manage your project billing at https://ai.studio/projects, or use the Prompt Builder & 6-Canvas Flow (which work 100% offline without API credits).',
      isBillingError: true,
      billingUrl: 'https://ai.studio/projects',
    };
  }

  return {
    error: errMsg || 'Operation failed',
    isBillingError: false,
  };
}

async function startServer() {
  const app = express();
  const server = http.createServer(app);

  app.use(express.json({ limit: '50mb' }));
  app.use(express.urlencoded({ extended: true, limit: '50mb' }));

  // ==========================================
  // 1. Image Creation & Editing (gemini-3.1-flash-image-preview)
  // ==========================================
  app.post('/api/gemini/image', async (req: Request, res: Response) => {
    try {
      const { prompt, image, mimeType, aspectRatio = '1:1' } = req.body;
      if (!prompt) {
        return res.status(400).json({ error: 'Prompt is required' });
      }

      let parts: any[] = [];
      if (image) {
        // Image editing or style reference
        const cleanBase64 = image.includes(',') ? image.split(',')[1] : image;
        parts = [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType || 'image/png',
            },
          },
          { text: prompt },
        ];
      } else {
        // Text-to-image creation
        parts = [{ text: prompt }];
      }

      const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image-preview',
        contents: { parts },
        config: {
          imageConfig: {
            aspectRatio: aspectRatio as any,
          },
        },
      });

      let imageUrl: string | null = null;
      let textResponse = '';

      const candidates = response.candidates || [];
      if (candidates[0]?.content?.parts) {
        for (const part of candidates[0].content.parts) {
          if (part.inlineData?.data) {
            imageUrl = `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
          } else if (part.text) {
            textResponse += part.text;
          }
        }
      }

      if (!imageUrl && !textResponse) {
        return res.status(500).json({ error: 'No image was generated by the model.' });
      }

      res.json({ imageUrl, text: textResponse });
    } catch (err: any) {
      console.error('Error generating image:', err);
      const formatted = formatGeminiError(err);
      res.status(formatted.isBillingError ? 402 : 500).json(formatted);
    }
  });

  // ==========================================
  // 2. Video Generation (veo-3.1-fast-generate-preview)
  // ==========================================
  app.post('/api/gemini/video-start', async (req: Request, res: Response) => {
    try {
      const { prompt, image, mimeType, aspectRatio = '16:9' } = req.body;

      const validAspect = aspectRatio === '9:16' ? '9:16' : '16:9';

      const config: any = {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: validAspect,
      };

      let operation;
      if (image) {
        const cleanBase64 = image.includes(',') ? image.split(',')[1] : image;
        operation = await ai.models.generateVideos({
          model: 'veo-3.1-fast-generate-preview',
          prompt: prompt || 'Animate this cinematic moment with smooth motion',
          image: {
            imageBytes: cleanBase64,
            mimeType: mimeType || 'image/png',
          },
          config,
        });
      } else {
        if (!prompt) {
          return res.status(400).json({ error: 'Prompt is required for video generation' });
        }
        operation = await ai.models.generateVideos({
          model: 'veo-3.1-fast-generate-preview',
          prompt,
          config,
        });
      }

      res.json({ operationName: operation.name });
    } catch (err: any) {
      console.error('Error starting video generation:', err);
      const formatted = formatGeminiError(err);
      res.status(formatted.isBillingError ? 402 : 500).json(formatted);
    }
  });

  app.post('/api/gemini/video-status', async (req: Request, res: Response) => {
    try {
      const { operationName } = req.body;
      if (!operationName) {
        return res.status(400).json({ error: 'operationName is required' });
      }

      const op = new GenerateVideosOperation();
      op.name = operationName;
      const updated = await ai.operations.getVideosOperation({ operation: op });

      res.json({
        done: Boolean(updated.done),
        error: updated.error || null,
      });
    } catch (err: any) {
      console.error('Error checking video status:', err);
      const formatted = formatGeminiError(err);
      res.status(formatted.isBillingError ? 402 : 500).json(formatted);
    }
  });

  app.post('/api/gemini/video-download', async (req: Request, res: Response) => {
    try {
      const { operationName } = req.body;
      if (!operationName) {
        return res.status(400).json({ error: 'operationName is required' });
      }

      const op = new GenerateVideosOperation();
      op.name = operationName;
      const updated = await ai.operations.getVideosOperation({ operation: op });

      const uri = updated.response?.generatedVideos?.[0]?.video?.uri;
      if (!uri) {
        return res.status(404).json({ error: 'Generated video URI not found' });
      }

      const videoRes = await fetch(uri, {
        headers: {
          'x-goog-api-key': process.env.GEMINI_API_KEY || '',
        },
      });

      if (!videoRes.ok) {
        throw new Error(`Failed to download video stream: ${videoRes.statusText}`);
      }

      res.setHeader('Content-Type', 'video/mp4');
      res.setHeader('Content-Disposition', 'inline; filename="generated-scene.mp4"');

      const arrayBuffer = await videoRes.arrayBuffer();
      res.send(Buffer.from(arrayBuffer));
    } catch (err: any) {
      console.error('Error downloading video:', err);
      const formatted = formatGeminiError(err);
      res.status(formatted.isBillingError ? 402 : 500).json(formatted);
    }
  });

  // ==========================================
  // 3. Gemini Multi-Turn Chatbot
  // ==========================================
  app.post('/api/gemini/chat', async (req: Request, res: Response) => {
    try {
      const { messages, model = 'gemini-3.8-flash', systemInstruction } = req.body;
      if (!messages || !Array.isArray(messages)) {
        return res.status(400).json({ error: 'messages array is required' });
      }

      // Format messages into contents array
      const contents = messages.map((m: any) => ({
        role: m.role === 'model' || m.role === 'assistant' ? 'model' : 'user',
        parts: [{ text: m.content || m.text || '' }],
      }));

      const defaultInstruction =
        'You are the AI Story Director and Creative Consultant for Scene + Script Kreator. ' +
        'You help users sharpen their three-scene story ideas, refine character motivations, improve dialogue, ' +
        'and ensure airtight continuity across Scene 1 (Hook), Scene 2 (Escalation), and Scene 3 (Payoff). ' +
        'Be insightful, concise, and focused on video production craft.';

      const chosenModel =
        model === 'gemini-3.1-pro-preview'
          ? 'gemini-3.1-pro-preview'
          : model === 'gemini-3.1-flash-lite'
          ? 'gemini-3.1-flash-lite'
          : 'gemini-3.8-flash';

      try {
        const response = await ai.models.generateContent({
          model: chosenModel,
          contents,
          config: {
            systemInstruction: systemInstruction || defaultInstruction,
          },
        });

        res.json({ text: response.text });
      } catch (firstErr: any) {
        // If higher model hit 402 or resource exhausted, try gemini-3.8-flash fallback
        if (chosenModel !== 'gemini-3.8-flash') {
          try {
            console.log(`Fallback from ${chosenModel} to gemini-3.8-flash...`);
            const fallbackResp = await ai.models.generateContent({
              model: 'gemini-3.8-flash',
              contents,
              config: {
                systemInstruction: systemInstruction || defaultInstruction,
              },
            });
            return res.json({ text: fallbackResp.text });
          } catch (secondErr: any) {
            const formatted = formatGeminiError(secondErr);
            return res.status(formatted.isBillingError ? 402 : 500).json(formatted);
          }
        }
        const formatted = formatGeminiError(firstErr);
        return res.status(formatted.isBillingError ? 402 : 500).json(formatted);
      }
    } catch (err: any) {
      console.error('Error in chat:', err);
      const formatted = formatGeminiError(err);
      res.status(formatted.isBillingError ? 402 : 500).json(formatted);
    }
  });

  // ==========================================
  // 4. Google Search Grounding
  // ==========================================
  app.post('/api/gemini/search', async (req: Request, res: Response) => {
    try {
      const { query } = req.body;
      if (!query) {
        return res.status(400).json({ error: 'query is required' });
      }

      const response = await ai.models.generateContent({
        model: 'gemini-3.8-flash',
        contents: query,
        config: {
          tools: [{ googleSearch: {} }],
        },
      });

      const groundingChunks =
        response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
      const sources = groundingChunks.map((c: any) => ({
        title: c.web?.title || 'Web Reference',
        uri: c.web?.uri || '',
      }));

      res.json({
        text: response.text,
        sources,
      });
    } catch (err: any) {
      console.error('Error with search grounding:', err);
      const formatted = formatGeminiError(err);
      res.status(formatted.isBillingError ? 402 : 500).json(formatted);
    }
  });

  // ==========================================
  // 5. Music Generation (lyria-3-clip-preview / lyria-3-pro-preview)
  // ==========================================
  app.post('/api/gemini/music', async (req: Request, res: Response) => {
    try {
      const { prompt, model = 'lyria-3-clip-preview' } = req.body;
      if (!prompt) {
        return res.status(400).json({ error: 'Prompt is required' });
      }

      const chosenModel = model === 'lyria-3-pro-preview' ? 'lyria-3-pro-preview' : 'lyria-3-clip-preview';

      const stream = await ai.models.generateContentStream({
        model: chosenModel,
        contents: prompt,
      });

      let audioBase64 = '';
      let lyrics = '';
      let mimeType = 'audio/wav';

      for await (const chunk of stream) {
        const parts = chunk.candidates?.[0]?.content?.parts;
        if (!parts) continue;
        for (const part of parts) {
          if (part.inlineData?.data) {
            if (!audioBase64 && part.inlineData.mimeType) {
              mimeType = part.inlineData.mimeType;
            }
            audioBase64 += part.inlineData.data;
          }
          if (part.text && !lyrics) {
            lyrics = part.text;
          }
        }
      }

      if (!audioBase64) {
        return res.status(500).json({ error: 'No audio was generated by Lyria.' });
      }

      res.json({
        audioUrl: `data:${mimeType};base64,${audioBase64}`,
        lyrics,
        mimeType,
      });
    } catch (err: any) {
      console.error('Error generating music:', err);
      const formatted = formatGeminiError(err);
      res.status(formatted.isBillingError ? 402 : 500).json(formatted);
    }
  });

  // ==========================================
  // 6. Voice Audio Preview (gemini-3.8-flash-lite-tts)
  // ==========================================
  app.post('/api/gemini/speech', async (req: Request, res: Response) => {
    try {
      const { text, voice = 'Kore' } = req.body;
      if (!text) {
        return res.status(400).json({ error: 'Text is required for TTS' });
      }

      const response = await ai.models.generateContent({
        model: 'gemini-3.8-flash-lite-tts',
        contents: [
          {
            role: 'user',
            parts: [{ text }],
          },
        ],
        config: {
          responseModalities: ['AUDIO'],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: voice },
            },
          },
        },
      });

      const base64Audio =
        response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;

      if (!base64Audio) {
        return res.status(500).json({ error: 'No audio synthesized.' });
      }

      res.json({
        audioUrl: `data:audio/wav;base64,${base64Audio}`,
      });
    } catch (err: any) {
      console.error('Error in TTS:', err);
      const formatted = formatGeminiError(err);
      res.status(formatted.isBillingError ? 402 : 500).json(formatted);
    }
  });

  // ==========================================
  // 7. Live API WebSocket Bridge (gemini-3.8-live)
  // ==========================================
  const wss = new WebSocketServer({ server, path: '/api/live-ws' });

  wss.on('connection', async (clientWs: WebSocket) => {
    console.log('Client connected to Live API WebSocket');
    let session: any = null;

    try {
      session = await ai.live.connect({
        model: 'gemini-3.8-live',
        config: {
          responseModalities: [Modality.AUDIO],
          speechConfig: {
            voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Zephyr' } },
          },
          systemInstruction:
            'You are an interactive live voice director for short-form video stories. ' +
            'Converse naturally and coach the user on story pacing and visual concepts.',
        },
        callbacks: {
          onmessage: (message: LiveServerMessage) => {
            const audio =
              message.serverContent?.modelTurn?.parts?.[0]?.inlineData?.data;
            if (audio && clientWs.readyState === WebSocket.OPEN) {
              clientWs.send(JSON.stringify({ audio }));
            }
            if (message.serverContent?.interrupted && clientWs.readyState === WebSocket.OPEN) {
              clientWs.send(JSON.stringify({ interrupted: true }));
            }
          },
        },
      });

      // Forward client audio to Gemini Live
      clientWs.on('message', async (data: any) => {
        try {
          const parsed = JSON.parse(data.toString());
          if (parsed.audio && session) {
            session.sendRealtimeInput({
              audio: { data: parsed.audio, mimeType: 'audio/pcm;rate=16000' },
            });
          }
        } catch (e) {
          console.error('Error forwarding client audio to Live API:', e);
        }
      });

      clientWs.on('close', () => {
        if (session) {
          try {
            session.close();
          } catch {}
        }
      });
    } catch (err) {
      console.error('Failed to initialize Live API session:', err);
      if (clientWs.readyState === WebSocket.OPEN) {
        clientWs.send(JSON.stringify({ error: 'Live API connection failed' }));
        clientWs.close();
      }
    }
  });

  // ==========================================
  // Vite Integration (Dev Middleware or Static Dist)
  // ==========================================
  if (process.env.NODE_ENV !== 'production') {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.resolve(__dirname, 'dist')));
    app.get('*', (_req: Request, res: Response) => {
      res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
    });
  }

  server.listen(PORT, '0.0.0.0', () => {
    console.log(`Scene + Script Kreator Server running at http://0.0.0.0:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error('Fatal server startup error:', err);
  process.exit(1);
});
