import { productionDirection } from './promptEngine';
import { buildDirectorPlan, formatSceneDirection } from './director-plan';
export type CanvasPlanItem={number:number;scene:number;type:'IMAGE'|'SCRIPT';title:string;role:string;instructions:string;};
export interface CanvasesData {mode:'planning';storyIdea:string;notice:string;continuity:string[];canvases:CanvasPlanItem[];}
export function buildCanvasPlan(input:Record<string,any>):CanvasesData{
 const details=input.optionalDetails||{};
 const idea=String(input.storyIdea||'Develop an original concept that fits the selected creative direction.');
 const direction=[`STORY IDEA: ${idea}`,input.characterType&&`CHARACTERS: ${input.characterType}`,input.genre&&`GENRE: ${input.genre}`,input.visualStyle&&`VISUAL STYLE: ${input.visualStyle}`,input.videoFormat&&`VIDEO FORMAT: ${input.videoFormat}`,input.energyTone&&`ENERGY / TONE: ${input.energyTone}`,details.era&&`ERA / TIME PERIOD: ${details.era}`,details.duration&&`REQUESTED DURATION: ${details.duration}`,details.storyGoal&&`STORY GOAL: ${details.storyGoal}`,details.obstacle&&`OBSTACLE / STAKES: ${details.obstacle}`,details.endingChange&&`ENDING / WHAT CHANGES: ${details.endingChange}`,details.characterGoals&&`CHARACTER GOALS: ${details.characterGoals}`,details.characterNames&&`CHARACTER NAMES & DESCRIPTIONS: ${details.characterNames}`,details.setting&&`SETTING: ${details.setting}`,details.productService&&`PRODUCT / SERVICE: ${details.productService}`,details.targetAudience&&`AUDIENCE: ${details.targetAudience}`].filter(Boolean).join('\n');
 const artDirection=productionDirection(input);
 const filmPlan=buildDirectorPlan(input.presets || input);
 const continuity=filmPlan.continuity;
 const beats=[{title:'Hook & Situation',role:'Establish the hook, main character, setting, and immediate situation.',transition:'Lead into a clear escalation or complication for Scene 2.'},{title:'Escalation & Turning Point',role:'Escalate, complicate, reveal, or deepen the situation introduced in Scene 1.',transition:'Build toward the payoff or resolution in Scene 3.'},{title:'Payoff & Resolution',role:'Resolve the central beat with a payoff, twist, punchline, reveal, or emotional close suited to the chosen format.',transition:'End cleanly. Do not introduce another unresolved scene.'}];
 if(filmPlan.format==='Trailer / Teaser'){beats[2]={title:'Teaser Payoff',role:'Deliver an earned reveal or teaser payoff that rewards the sequence while leaving the central story question open.',transition:'End cleanly on the teaser beat without introducing an unrelated subplot.'};}
 const canvases:CanvasPlanItem[]=[];
 beats.forEach((beat,i)=>{
  const scene=i+1;
  const sceneDirection=formatSceneDirection(filmPlan.scenes[i]);
  const sharedDirection=[filmPlan.framing,filmPlan.medium,`Lighting: ${filmPlan.lighting}`,`Performance: ${filmPlan.performance}`, ...filmPlan.notes].join('\n');
  const continuityText=continuity.map(rule=>`- ${rule}`).join('\n');
  canvases.push({number:i*2+1,scene,type:'IMAGE',title:`Scene ${scene} Image`,role:beat.title,instructions:`CREATE ONE FINISHED IMAGE FOR SCENE ${scene}\n\n${direction}\n\nART & PERFORMANCE DIRECTION\n${artDirection || 'Choose one coherent visual treatment appropriate to the story.'}\n\nAUTOMATIC FILM DIRECTION\n${sharedDirection}\n${sceneDirection}\n\nSCENE OBJECTIVE\n${beat.role}\n\nIMAGE DIRECTION\nChoose one decisive visual moment that communicates this objective, with one dominant beat and one primary focal subject. Include the exact locked character and setting details, then identify any story-driven changes since the prior scene. Specify prop placement and spatial relationships. Specify shot size, camera height, lens perspective, foreground and background depth, focus placement, motivated key light, contact shadows and tactile material response. Direct a specific gesture, eyeline and emotional reaction. Show a single scene only: no collage, grid, split-screen, contact sheet, or alternate versions.\n\nCONTINUITY\n${continuityText}\n\nSEQUENCE\n${beat.transition}`});
  canvases.push({number:i*2+2,scene,type:'SCRIPT',title:`Scene ${scene} Script`,role:beat.title,instructions:`WRITE THE PRODUCTION SCRIPT FOR SCENE ${scene}\n\n${direction}\n\nART & PERFORMANCE DIRECTION\n${artDirection || 'Choose one coherent visual treatment appropriate to the story.'}\n\nAUTOMATIC FILM DIRECTION\n${sharedDirection}\n${sceneDirection}\n\nSCENE OBJECTIVE\n${beat.role}\n\nINCLUDE\n- An estimated duration appropriate to the selected video format\n- Action and performance direction that matches the visible or imminent action in the Scene ${scene} image\n- Natural dialogue and/or voiceover that advances this story beat\n- On-screen text only when useful or explicitly supplied, separate from spoken dialogue\n- Sound, music, or SFX cues when useful\n- Shot size, lens perspective, motivated camera movement, blocking and eyelines\n- Light sources, secondary motion, reaction holds and sound perspective\n- Camera and edit notes\n- Transition: ${beat.transition}${scene===2&&details.dialogueMustHaves?`\n\nREQUIRED DIALOGUE / VOICEOVER\nUse these exact spoken words once in this scene unless the written story specifies another placement: "${details.dialogueMustHaves}"`:''}${scene===3&&details.onScreenText?`\n\nEXACT ON-SCREEN TEXT\nDisplay these exact words once, legibly, in this scene unless the written story specifies another placement. Do not turn them into spoken dialogue: "${details.onScreenText}"`:''}${scene===3&&details.callToAction?`\n\nCALL TO ACTION\n${details.callToAction}`:''}\n\nCONTINUITY\n${continuityText}\n\nKeep the script concise, performable, and consistent with all earlier scenes. Treat product/service details as context; do not invent claims or an unrequested sales pitch.`});
 });
 return {mode:'planning',storyIdea:idea,notice:'This is a structured planning template, not AI-written scenes or finished images. Copy the master prompt into ChatGPT to create the complete story.',continuity,canvases};
}
export function planAsText(data:CanvasesData){return `SCENE & SCRIPT STUDIO — SIX-CANVAS PLAN\n\n${data.notice}\n\n${data.canvases.map(c=>`CANVAS ${c.number}: ${c.title}\n\n${c.instructions}`).join('\n\n'+'—'.repeat(50)+'\n\n')}`;}
